name: Generate Resume PDF and DOCX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm \
          libnss3 libx11-xcb1 libxcomposite1 libxcursor1 \
          libxdamage1 libxi6 libxtst6 libatk1.0-0 libpango-1.0-0 \
          libcups2 libxrandr2 libasound2 libpangocairo-1.0-0 \
          libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev
          npm install html-docx-js puppeteer
      
      - name: Generate PDF with Puppeteer
        run: |
          echo 'Generating PDF...'
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
              const browser = await puppeteer.launch({
                  headless: true,
                  args: ['--no-sandbox', '--disable-setuid-sandbox']
              });
              const page = await browser.newPage();
              await page.goto('file://$(pwd)/index.html', { waitUntil: 'networkidle2' });
              await page.pdf({ path: 'resume.pdf', format: 'A4' });
              await browser.close();
          })();
          "
        
      - name: Generate DOCX with html-docx-js
        run: |
          echo 'Generating DOCX...'
          node -e "
          const fs = require('fs');
          const htmlDocx = require('html-docx-js');
          (async () => {
              const html = fs.readFileSync('index.html', 'utf-8');
              const docxBlob = htmlDocx.asBlob(html);
              const buffer = Buffer.from(await docxBlob.arrayBuffer()); // Convert Blob to Buffer
              fs.writeFileSync('resume.docx', buffer);
          })();
          "
      
      - name: Upload Generated Files
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: resume-files
          path: |
            resume.pdf
            resume.docx
      
      - name: Upload Generated Files Locally (for act)
        if: ${{ env.ACT }}
        run: |
          mkdir -p /workspace/html-to-pdf-and-docx/artifacts
          mv resume.pdf /workspace/html-to-pdf-and-docx/artifacts/
          mv resume.docx /workspace/html-to-pdf-and-docx/artifacts/