name: Generate Resume PDF and DOCX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf nodejs npm
          npm install html-docx-js puppeteer
      
      - name: Generate PDF with Puppeteer
        run: |
          echo 'Generating PDF...'
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('file://$(pwd)/index.html', { waitUntil: 'networkidle2' });
              await page.pdf({ path: 'resume.pdf', format: 'A4' });
              await browser.close();
          })();
          "
        
      - name: Generate DOCX with html-docx-js
        run: |
          echo 'Generating DOCX...'
          node -e "
          const fs = require('fs');
          const htmlDocx = require('html-docx-js');
          const html = fs.readFileSync('index.html', 'utf-8');
          const docx = htmlDocx.asBlob(html);
          fs.writeFileSync('resume.docx', docx);
          "
      
      - name: Upload Generated Files
        uses: actions/upload-artifact@v4
        with:
          name: resume-files
          path: |
            resume.pdf
            resume.docx
